### ISSUE TITLE
express could not find file in memory ... another issue solved it 

### ISSUE THREAD

**Issue by rowntreerob** [bengrunfeld/expack#10]
after npm install and webpack on the 2 config files , i run and get following errs .... 

Error: no such file or directory
    at MemoryFileSystem.readFileSync (/home/rob/src/node-speech/node_modules/memory-fs/lib/MemoryFileSystem.js:114:10)
    at MemoryFileSystem.(anonymous function) [as readFile] (/home/rob/src/node-speech/node_modules/memory-fs/lib/MemoryFileSystem.js:300:34)
    at eval (webpack:///./src/server/server-dev.js?:29:29)
    at Layer.handle [as handle_request] (/home/rob/src/node-speech/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/rob/src/node-speech/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/rob/src/node-speech/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/rob/src/node-speech/node_modules/express/lib/router/layer.js:95:5)
    at /home/rob/src/node-speech/node_modules/express/lib/router/index.js:281:22
    at param (/home/rob/src/node-speech/node_modules/express/lib/router/index.js:354:14)
    at param (/home/rob/src/node-speech/node_modules/express/lib/router/index.js:365:14)
Er

line 29 block is:  app.get('*'  

your new code :

```
app.get('*', (req, res, next) => {

  var filename = path.join(compiler.outputPath,'index.html');
  compiler.outputFileSystem.readFile(filename, (err, result) => {
```

[soliution_ref ](https://github.com/jantimon/html-webpack-plugin/issues/145#issuecomment-170554832)

**Comment by kimgysen** [comment]
Is this another abandoned project?

**Comment by anoopsankar** [comment]
Your HTML should contain this tag or you should provide a favico on your root.
`<link rel="shortcut icon" href="#">`
