### ISSUE TITLE
Can't run (buildDev, buildProd) : Cannot read 'properties' of undefined 

### ISSUE THREAD

**Issue by EliasTouil** [bengrunfeld/expack#2]
Dear Ben, 

I'm unable to run the boilerplate

### Steps
- Downloaded and unzipped
- Placed in some "~/projects/" folder
- Deleted package-lock.json
- ran npm install
- ran npm run buildDev (buildProd sends same error)

### Error Message

```
> expack@1.0.0 buildProd /Users/eliastouil/Google Drive/Programmation/paintball-iot/xyz-faker
> rm -rf dist && webpack --mode production --config webpack.server.config.js && webpack --mode production --config webpack.prod.config.js

/Users/eliastouil/Google Drive/Programmation/paintball-iot/xyz-faker/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/eliastouil/Google Drive/Programmation/paintball-iot/xyz-faker/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/eliastouil/Google Drive/Programmation/paintball-iot/xyz-faker/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/eliastouil/Google Drive/Programmation/paintball-iot/xyz-faker/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! expack@1.0.0 buildProd: `rm -rf dist && webpack --mode production --config webpack.server.config.js && webpack --mode production --config webpack.prod.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the expack@1.0.0 buildProd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eliastouil/.npm/_logs/2018-12-29T02_13_25_019Z-debug.log
Eliass-MacBook-Pro:xyz-faker eliastouil$
```

_Thank you for your help_

**Comment by bengrunfeld** [comment]
I've updated the npm packages. Please `git pull` or clone/download the new version and run `npm install` on it. This was likely an issue with and older version of `webpack-cli`, and several other users ran into it. I'm closing this issue, but please re-open if the bug persists.
